# Generated by Django 5.2.16 on 2026-08-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ghl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('queued', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('partial', 'Partiellement terminée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20)),
                ('created_by_highlevel_user_id', models.CharField(max_length=120)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_campaigns', to='ghl.ghlinstallation')),
            ],
        ),
        migrations.CreateModel(
            name='BulkCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_contact_id', models.CharField(max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('normalized_phone', models.CharField(max_length=30)),
                ('rendered_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], db_index=True, default='pending', max_length=20)),
                ('evolution_message_id', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.bulkcampaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'ghl_contact_id'), name='unique_contact_per_bulk_campaign')],
            },
        ),
    ]
