# Generated by Django 5.2.16 on 2026-08-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='is_on_whatsapp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='not_on_whatsapp_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='validated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='validation_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='whatsapp_check_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='whatsapp_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='whatsapp_jid',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('queued', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('partial', 'Partiellement terminée'), ('failed', 'Échec'), ('cancelled', 'Annulée'), ('not_on_whatsapp', 'Pas sur WhatsApp')], db_index=True, default='draft', max_length=20),
        ),
    ]
