# Generated by Django 5.2.16 on 2026-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_bulkcampaign_is_on_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcampaignrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré'), ('validated', 'Validé')], db_index=True, default='pending', max_length=20),
        ),
    ]
