# Generated by Django 5.2.16 on 2026-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_bulkcampaignrecipient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='is_on_whatsapp',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='whatsapp_check_error',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='whatsapp_checked_at',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='whatsapp_jid',
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='is_on_whatsapp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='whatsapp_check_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='whatsapp_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='whatsapp_jid',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('queued', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('partial', 'Partiellement terminée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkcampaignrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validating', 'Vérification WhatsApp'), ('ready', 'Prêt à envoyer'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré'), ('not_on_whatsapp', 'Pas sur WhatsApp')], db_index=True, default='pending', max_length=20),
        ),
    ]
