# Generated by Django 5.2.16 on 2026-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_bulkcampaign_is_on_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='ghl_conversation_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='ghl_history_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='ghl_message_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='provider_delivery_status',
            field=models.CharField(choices=[('pending', 'En attente GHL'), ('submitted', 'Transmis à GHL'), ('sent', 'Envoyé par le provider'), ('failed', 'Échec du provider')], db_index=True, default='pending', max_length=20),
        ),
    ]
