# Generated by Django 5.2.16 on 2026-08-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_bulkcampaignrecipient_ghl_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='relaunch_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='source_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaunches', to='messaging.bulkcampaign'),
        ),
        migrations.AddField(
            model_name='bulkcampaignrecipient',
            name='evolution_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaigns/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.bulkcampaign')),
            ],
        ),
    ]
