# Generated by Django 5.2.16 on 2026-08-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ghl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=120, unique=True)),
                ('remote_instance_id', models.CharField(blank=True, max_length=150)),
                ('integration', models.CharField(default='WHATSAPP-BAILEYS', max_length=50)),
                ('instance_api_key', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Créée'), ('connecting', 'Connexion en cours'), ('open', 'Connectée'), ('close', 'Déconnectée'), ('error', 'Erreur')], default='created', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_instance', to='ghl.ghlinstallation')),
            ],
        ),
    ]
