# Generated by Django 5.2.16 on 2026-08-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutioninstance',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('deduplication_key', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processing', 'En traitement'), ('processed', 'Traité'), ('failed', 'Échec'), ('ignored', 'Ignoré')], db_index=True, default='received', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='evolution.evolutioninstance')),
            ],
        ),
    ]
